export const IngestionProviders = {
  INGESTION_REPOSITORY: Symbol("INGESTION_REPOSITORY"),
  TRANSCRIPT_REPOSITORY: Symbol("TRANSCRIPT_REPOSITORY"),
  SYLLABUS_REPOSITORY: Symbol("SYLLABUS_REPOSITORY"),
  OUTBOX_REPOSITORY: Symbol("OUTBOX_REPOSITORY"),
  SYLLABUS_DATA_SOURCE: Symbol("SYLLABUS_DATA_SOURCE"),
  ADAPTER_SELECTOR: Symbol("ADAPTER_SELECTOR"),
  CHULA_ADAPTER: Symbol("CHULA_ADAPTER"),
  KMITL_ADAPTER: Symbol("KMITL_ADAPTER"),
} as const;
