/**
 * Dependency Injection Tokens for Ingestion Module
 * Centralized enum to prevent typos and improve maintainability
 */
export enum IngestionProviders {
  INGESTION_REPOSITORY = "INGESTION_REPOSITORY",
  TRANSCRIPT_REPOSITORY = "TRANSCRIPT_REPOSITORY",
  SYLLABUS_REPOSITORY = "SYLLABUS_REPOSITORY",
  OUTBOX_REPOSITORY = "OUTBOX_REPOSITORY",
  SYLLABUS_DATA_SOURCE = "SYLLABUS_DATA_SOURCE",
  ADAPTER_SELECTOR = "ADAPTER_SELECTOR",
  CHULA_ADAPTER = "CHULA_ADAPTER",
  KMITL_ADAPTER = "KMITL_ADAPTER",
}
